
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT __init__:app

runtime_config:
    python_version: 3


beta_settings:
    cloud_sql_instances: overwatchglam-181020:us-central1:overwatch2
skip_files:
- env
- .git
- __pycache__
- .pyc

# [END handlers]
